In [19]:
import pandas as pd
import numpy as np

In [17]:
data_drill1617 = pd.read_excel(r'Data Sources/accdrilldwn1617_4pandas.xlsx')

In [20]:
data_drill1617.columns

Index(['District Name', 'School Code', 'School Name', 'SBE District',
       'Subject', 'Standard (CCR - Level 4 & 5, GLP - Level 3 & Above)',
       'All Students', 'Female', ' Male', 'American Indian', 'Asian', 'Black',
       'Hispanic', 'Two or More Races', ' White', 'EDS', 'LEP', 'SWD', 'AIG',
       'All Students.1', 'Female.1', ' Male.1', 'American Indian.1', 'Asian.1',
       'Black.1', 'Hispanic.1', 'Two or More Races.1', ' White.1', 'EDS.1',
       'LEP.1', 'SWD.1', 'AIG.1'],
      dtype='object')

In [24]:
data_drill1617_df = pd.DataFrame(data_drill1617, columns=['District Name', 'School Code', 'School Name', 'Subject', 'All Students', 'Female', ' Male', 'Black', 'Hispanic', ' White'])

In [25]:
data_drill1617_df

,District Name,School Code,School Name,Subject,All Students,Female,Male,Black,Hispanic,White
0,State of North Carolina,NC,State of North Carolina,All EOG/EOC Subjects,49.2,51.0,47.6,29.7,37.6,62.0
1,State of North Carolina,NC,State of North Carolina,All EOC Subjects,50.9,54.0,48.0,29.8,39.4,63.2
2,State of North Carolina,NC,State of North Carolina,EOC Biology,47.5,48.5,46.5,26.7,35.5,60.3
3,State of North Carolina,NC,State of North Carolina,EOC English 2,50.1,56.0,44.4,30.8,38.5,62.6
4,State of North Carolina,NC,State of North Carolina,EOC Math I,54.1,56.6,51.8,31.5,42.9,65.8
...,...,...,...,...,...,...,...,...,...,...
85761,Charter Schools,98B000,Wilson Preparatory Academy,EOG Math Grade 8,62.7,59.1,65.5,42.9,*,73.1
85762,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grades 5&8,89.8,90.2,89.5,80.0,*,94.2
85763,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 5,87.2,89.5,85.7,78.6,*,88.5
85764,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95
85765,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95

In [27]:
data_drill1617_df['District Name'].value_counts()

Charter Schools                  7808
Charlotte-Mecklenburg Schools    5326
Wake County Schools              5323
Guilford County Schools          3640
Cumberland County Schools        2445
                                 ...
Graham County Schools             150
Clay County Schools               148
State of North Carolina            69
Deaf and Blind Schools             51
Regional Schools                   20
Name: District Name, Length: 119, dtype: int64

In [36]:
df_charmeck1617 = data_drill1617_df.loc[df3['District Name'] == "Charlotte-Mecklenburg Schools"]

In [44]:
df_charmeck1617

,District Name,School Code,School Name,Subject,All Students,Female,Male,Black,Hispanic,White
0,Charlotte-Mecklenburg Schools,NC,State of North Carolina,All EOG/EOC Subjects,49.2,51.0,47.6,29.7,37.6,62.0
1,Charlotte-Mecklenburg Schools,NC,State of North Carolina,All EOC Subjects,50.9,54.0,48.0,29.8,39.4,63.2
2,Charlotte-Mecklenburg Schools,NC,State of North Carolina,EOC Biology,47.5,48.5,46.5,26.7,35.5,60.3
3,Charlotte-Mecklenburg Schools,NC,State of North Carolina,EOC English 2,50.1,56.0,44.4,30.8,38.5,62.6
4,Charlotte-Mecklenburg Schools,NC,State of North Carolina,EOC Math I,54.1,56.6,51.8,31.5,42.9,65.8
...,...,...,...,...,...,...,...,...,...,...
85761,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Math Grade 8,62.7,59.1,65.5,42.9,*,73.1
85762,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grades 5&8,89.8,90.2,89.5,80.0,*,94.2
85763,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 5,87.2,89.5,85.7,78.6,*,88.5
85764,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95
85765,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95

In [37]:
df_charmeck1617.columns

Index(['District Name', 'School Code', 'School Name', 'Subject',
       'All Students', 'Female', ' Male', 'Black', 'Hispanic', ' White'],
      dtype='object')

In [40]:
df_charmeck1617['District Name'].value_counts()

Charlotte-Mecklenburg Schools    85766
Name: District Name, dtype: int64

In [41]:
df_charmeck1617['School Code'].value_counts()

NC        69
400       69
520       69
510       69
080       69
          ..
920703     1
150700     1
240318     1
920701     1
340398     1
Name: School Code, Length: 2694, dtype: int64

In [42]:
df_charmeck1617['School Name'].value_counts()

Central Elementary                          200
Union Elementary                            170
Bethel Elementary                           164
Southwest Elementary                        150
Fairview Elementary                         144
                                           ...
Blue Ridge Academy                            7
Person Early College Innovation & Ldrshp      6
Alexander Early College                       6
The Special Children's School                 6
Homebound/ Hospital Education                 1
Name: School Name, Length: 2586, dtype: int64

In [43]:
df_charmeck1617['Subject'].value_counts()

All EOG/EOC Subjects         5358
All EOG Subjects             4346
EOG Reading Grades 3-8       4334
EOG Math Grades 3-8          4334
EOG Science Grades 5&8       4098
EOG Grade 4                  3158
EOG Grade 3                  3156
EOG Math Grade 3             3136
EOG Reading Grade 3          3136
EOG Math Grade 4             3128
EOG Reading Grade 4          3128
EOG Grade 5                  3108
EOG Science Grade 5          3064
EOG Math Grade 5             3064
EOG Reading Grade 5          3064
All EOC Subjects             2546
EOC Math I                   2486
EOG Grade 6                  1768
EOG Reading Grade 6          1712
EOG Math Grade 6             1712
EOG Grade 8                  1700
EOG Grade 7                  1700
EOG Science Grade 8          1647
EOG Math Grade 8             1646
EOG Reading Grade 8          1646
EOG Reading Grade 7          1628
EOG Math Grade 7             1628
EOC English 2                1454
EOC Biology                  1442
Graduation Rate              1414
The ACT - All Subtests        729
Math Course Rigor             687
The ACT - English             683
The ACT - Reading             683
The ACT - Composite Score     682
The ACT - Math                682
The ACT - Science             682
The ACT - Writing             678
ACT WorkKeys                  519
Name: Subject, dtype: int64

In [49]:
# G9_math_data = cs_df.loc[(cs_df["math_score"]) & (cs_df["grade"]=="9th") ,:]
# df_charmeck1617_kpi = df_charmeck1617.loc[(df_charmeck1617['Subject']== "The ACT - Composite Score") & (df_charmeck1617['Subject']== "Graduation Rate") & (df_charmeck1617['Subject']== "ACT WorkKeys")]

In [68]:
df_charmeck1617_kpi['Subject'].value_counts

<bound method IndexOpsMixin.value_counts of 58                 Graduation Rate
59                 Graduation Rate
60       The ACT - Composite Score
68                    ACT WorkKeys
127                Graduation Rate
                   ...
85258    The ACT - Composite Score
85462              Graduation Rate
85463              Graduation Rate
85474              Graduation Rate
85475    The ACT - Composite Score
Name: Subject, Length: 2615, dtype: object>

In [62]:
Acad_kpi = df_charmeck1617['Subject'].isin(["The ACT - Composite Score", "ACT WorkKeys", "Graduation Rate"])

In [63]:
df_charmeck1617_kpi = df_charmeck1617[Acad_kpi]
len(df_charmeck1617_kpi)

2615

In [64]:
df_charmeck1617_kpi

,District Name,School Code,School Name,Subject,All Students,Female,Male,Black,Hispanic,White
58,Charlotte-Mecklenburg Schools,NC,State of North Carolina,Graduation Rate,86.5,89.7,83.5,83.9,80.5,89.3
59,Charlotte-Mecklenburg Schools,NC,State of North Carolina,Graduation Rate,87.5,90.2,84.9,85.3,82.7,89.7
60,Charlotte-Mecklenburg Schools,NC,State of North Carolina,The ACT - Composite Score,58.8,62.2,55.4,34.7,44.2,73.0
68,Charlotte-Mecklenburg Schools,NC,State of North Carolina,ACT WorkKeys,73.3,73.2,73.4,56.5,72.0,80.5
127,Charlotte-Mecklenburg Schools,010,Alamance-Burlington Schools,Graduation Rate,82.4,86.9,77.9,81.9,75.1,85.1
...,...,...,...,...,...,...,...,...,...,...
85258,Charlotte-Mecklenburg Schools,92U000,Longleaf School of the Arts,The ACT - Composite Score,82.9,84.3,78.9,41.7,*,>95
85462,Charlotte-Mecklenburg Schools,93A000,Haliwa-Saponi Tribal School,Graduation Rate,70.0,90.9,*,*,*,*
85463,Charlotte-Mecklenburg Schools,93A000,Haliwa-Saponi Tribal School,Graduation Rate,75.0,*,66.7,*,*,*
85474,Charlotte-Mecklenburg Schools,93L000,Central Wake Charter High,Graduation Rate,23.4,28.6,19.2,21.4,8.3,*
85475,Charlotte-Mecklenburg Schools,93L000,Central Wake Charter High,The ACT - Composite Score,16.7,16.7,*,<5,*,*

In [ ]:
# schools = [school_name,LEA
# Ardrey Kell High School,600302
# Butler High School,600361
# Cato Middle College High School,600334
# Charlotte Engineering Early College,600567
# Charlotte Teacher Early College,
# Charlotte-Mecklenburg Virtual High School,
# East Mecklenburg High School,600377
# Garinger High School,600397
# Harding University High School,600405
# Harper Middle College High School,600404
# Hawthorne Academy of Health Sciences,600386
# Hopewell High School,600415
# Independence High School,600426
# John Taylor Williams Secondary Montessori,
# Julius L. Chambers High School,
# Levine Middle College High,600443
# Mallard Creek High School,600445
# Merancas Middle College @ CPCC,
# Military and Global Leadership Academy,600364
# Myers Park High School,600466
# North Mecklenburg High School,600480
# Northwest School of the Arts,600482
# Olympic High School,
# Performance Learning Center,600498
# Phillip O. Berry Academy of Technology,600496
# Providence High School,600508
# Rocky River High School,600457
# South Mecklenburg High School,600535
# West Charlotte High School,600576
# West Mecklenburg High School,600579
# William Amos Hough High School,600312
# Turning Point Academy,
# Charlotte-Mecklenburg Academy,
# Metro School,
# ]