In [19]:
import pandas as pd
import numpy as np

In [17]:
df2 = pd.read_excel(r'Data Sources/accdrilldwn1617_4pandas.xlsx')

In [20]:
df2.columns

Index(['District Name', 'School Code', 'School Name', 'SBE District',
       'Subject', 'Standard (CCR - Level 4 & 5, GLP - Level 3 & Above)',
       'All Students', 'Female', ' Male', 'American Indian', 'Asian', 'Black',
       'Hispanic', 'Two or More Races', ' White', 'EDS', 'LEP', 'SWD', 'AIG',
       'All Students.1', 'Female.1', ' Male.1', 'American Indian.1', 'Asian.1',
       'Black.1', 'Hispanic.1', 'Two or More Races.1', ' White.1', 'EDS.1',
       'LEP.1', 'SWD.1', 'AIG.1'],
      dtype='object')

In [24]:
df3 = pd.DataFrame(df2, columns=['District Name', 'School Code', 'School Name', 'Subject', 'All Students', 'Female', ' Male', 'Black', 'Hispanic', ' White'])

In [25]:
df3

,District Name,School Code,School Name,Subject,All Students,Female,Male,Black,Hispanic,White
0,State of North Carolina,NC,State of North Carolina,All EOG/EOC Subjects,49.2,51.0,47.6,29.7,37.6,62.0
1,State of North Carolina,NC,State of North Carolina,All EOC Subjects,50.9,54.0,48.0,29.8,39.4,63.2
2,State of North Carolina,NC,State of North Carolina,EOC Biology,47.5,48.5,46.5,26.7,35.5,60.3
3,State of North Carolina,NC,State of North Carolina,EOC English 2,50.1,56.0,44.4,30.8,38.5,62.6
4,State of North Carolina,NC,State of North Carolina,EOC Math I,54.1,56.6,51.8,31.5,42.9,65.8
...,...,...,...,...,...,...,...,...,...,...
85761,Charter Schools,98B000,Wilson Preparatory Academy,EOG Math Grade 8,62.7,59.1,65.5,42.9,*,73.1
85762,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grades 5&8,89.8,90.2,89.5,80.0,*,94.2
85763,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 5,87.2,89.5,85.7,78.6,*,88.5
85764,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95
85765,Charter Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95

In [27]:
df3['District Name'].value_counts()

Charter Schools                  7808
Charlotte-Mecklenburg Schools    5326
Wake County Schools              5323
Guilford County Schools          3640
Cumberland County Schools        2445
                                 ...
Graham County Schools             150
Clay County Schools               148
State of North Carolina            69
Deaf and Blind Schools             51
Regional Schools                   20
Name: District Name, Length: 119, dtype: int64

In [34]:
df_charmeck = df3.loc[df3['District Name']=="Charlotte-Mecklenburg Schools"]

In [35]:
df_charmeck.

,District Name,School Code,School Name,Subject,All Students,Female,Male,Black,Hispanic,White
0,Charlotte-Mecklenburg Schools,NC,State of North Carolina,All EOG/EOC Subjects,49.2,51.0,47.6,29.7,37.6,62.0
1,Charlotte-Mecklenburg Schools,NC,State of North Carolina,All EOC Subjects,50.9,54.0,48.0,29.8,39.4,63.2
2,Charlotte-Mecklenburg Schools,NC,State of North Carolina,EOC Biology,47.5,48.5,46.5,26.7,35.5,60.3
3,Charlotte-Mecklenburg Schools,NC,State of North Carolina,EOC English 2,50.1,56.0,44.4,30.8,38.5,62.6
4,Charlotte-Mecklenburg Schools,NC,State of North Carolina,EOC Math I,54.1,56.6,51.8,31.5,42.9,65.8
...,...,...,...,...,...,...,...,...,...,...
85761,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Math Grade 8,62.7,59.1,65.5,42.9,*,73.1
85762,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grades 5&8,89.8,90.2,89.5,80.0,*,94.2
85763,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 5,87.2,89.5,85.7,78.6,*,88.5
85764,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95
85765,Charlotte-Mecklenburg Schools,98B000,Wilson Preparatory Academy,EOG Science Grade 8,92.2,90.9,93.1,81.0,*,>95