In [1]:
import pandas as pd
import seaborn as sns

In [2]:
sixteen = pd.read_csv("sixteen_to_sql.csv")

C:\Users\Alexander Saunders\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [3]:
sixteen.head()

,District Name,School Code,School Name,SBE District,Subject,"Standard (CCR - Level 4 & 5, GLP - Level 3 & Above)",All Students,Female,Male,American Indian,...,American Indian.1,Asian.1,Black.1,Hispanic.1,Two or More Races.1,White.1,EDS.1,LEP.1,SWD.1,AIG.1
0,State of North Carolina,NC,State of North Carolina,NaN,All EOG/EOC Subjects,College and Career Ready,49.2,51.0,47.6,33.4,...,24464,64469,509546,342683,83948,998834,995415,95195,255617,305064
1,State of North Carolina,NC,State of North Carolina,NaN,All EOC Subjects,College and Career Ready,50.9,54.0,48.0,33.6,...,4598,12697,96147,57565,14718,200303,170107,13634,42229,76138
2,State of North Carolina,NC,State of North Carolina,NaN,EOC Biology,College and Career Ready,47.5,48.5,46.5,33.0,...,1435,3592,29523,16915,4258,58641,50089,3627,12962,19977
3,State of North Carolina,NC,State of North Carolina,NaN,EOC English 2,College and Career Ready,50.1,56.0,44.4,30.9,...,1464,3542,31119,17970,4508,61362,54188,4153,13851,20321
4,State of North Carolina,NC,State of North Carolina,NaN,EOC Math I,College and Career Ready,54.1,56.6,51.8,36.5,...,1699,5563,35505,22680,5952,80300,65830,5854,15416,35840

In [5]:
sixteen['District Name'].unique()

array(['State of North Carolina', 'Alamance-Burlington Schools',
       'Alexander County Schools', 'Alleghany County Schools',
       'Anson County Schools', 'Ashe County Schools',
       'Avery County Schools', 'Beaufort County Schools',
       'Bertie County Schools', 'Bladen County Schools',
       'Brunswick County Schools', 'Buncombe County Schools',
       'Asheville City Schools', 'Burke County Schools',
       'Cabarrus County Schools', 'Kannapolis City Schools',
       'Caldwell County Schools', 'Camden County Schools',
       'Carteret County Public Schools', 'Caswell County Schools',
       'Catawba County Schools', 'Hickory City Schools',
       'Newton Conover City Schools', 'Chatham County Schools',
       'Cherokee County Schools', 'Edenton-Chowan Schools',
       'Clay County Schools', 'Cleveland County Schools',
       'Columbus County Schools', 'Whiteville City Schools',
       'Craven County Schools', 'Cumberland County Schools',
       'Currituck County Schools', 'Dare County Schools',
       'Davidson County Schools', 'Lexington City Schools',
       'Thomasville City Schools', 'Deaf and Blind Schools',
       'Davie County Schools', 'Duplin County Schools',
       'Durham Public Schools', 'Edgecombe County Public School',
       'Forsyth County Schools', 'Franklin County Schools',
       'Gaston County Schools', 'Gates County Schools',
       'Graham County Schools', 'Granville County Schools',
       'Greene County Schools', 'Guilford County Schools',
       'Halifax County Schools', 'Roanoke Rapids City Schools',
       'Weldon City Schools', 'Harnett County Schools',
       'Haywood County Schools', 'Henderson County Schools',
       'Hertford County Schools', 'Hoke County Schools',
       'Hyde County Schools', 'Iredell-Statesville Schools',
       'Mooresville City Schools', 'Jackson County Schools',
       'Johnston County Schools', 'Jones County Schools',
       'Lee County Schools', 'Lenoir County Public Schools',
       'Lincoln County Schools', 'Macon County Schools',
       'Madison County Schools', 'Martin County Schools',
       'McDowell County Schools', 'Charlotte-Mecklenburg Schools',
       'Mitchell County Schools', 'Montgomery County Schools',
       'Moore County Schools', 'Nash-Rocky Mount Schools',
       'New Hanover County Schools', 'Northampton County Schools',
       'Onslow County Schools', 'Orange County Schools',
       'Chapel Hill-Carrboro Schools', 'Pamlico County Schools',
       'Pasquotank County Schools', 'Pender County Schools',
       'Perquimans County Schools', 'Person County Schools',
       'Pitt County Schools', 'Polk County Schools',
       'Randolph County Schools', 'Asheboro City Schools',
       'Richmond County Schools', 'Robeson County Schools',
       'Rockingham County Schools', 'Rowan-Salisbury Schools',
       'Rutherford County Schools', 'Sampson County Schools',
       'Clinton City Schools', 'Scotland County Schools',
       'Stanly County Schools', 'Stokes County Schools',
       'Surry County Schools', 'Elkin City Schools',
       'Mount Airy City Schools', 'Swain County Schools',
       'Transylvania County Schools', 'Tyrrell County Schools',
       'Union County Public Schools', 'Vance County Schools',
       'Wake County Schools', 'Warren County Schools',
       'Washington County Schools', 'Watauga County Schools',
       'Wayne County Public Schools', 'Wilkes County Schools',
       'Wilson County Schools', 'Yadkin County Schools',
       'Yancey County Schools', 'Regional Schools', 'Charter Schools'],
      dtype=object)

In [6]:
char_meck = sixteen.loc[sixteen['District Name'] == 'Charlotte-Mecklenburg Schools']

In [9]:
char_meck.columns

Index(['District Name', 'School Code', 'School Name', 'SBE District',
       'Subject', 'Standard (CCR - Level 4 & 5, GLP - Level 3 & Above)',
       'All Students', 'Female', ' Male', 'American Indian', 'Asian', 'Black',
       'Hispanic', 'Two or More Races', ' White', 'EDS', 'LEP', 'SWD', 'AIG',
       'All Students.1', 'Female.1', ' Male.1', 'American Indian.1', 'Asian.1',
       'Black.1', 'Hispanic.1', 'Two or More Races.1', ' White.1', 'EDS.1',
       'LEP.1', 'SWD.1', 'AIG.1'],
      dtype='object')

In [14]:
char_meck['Subject'].unique()

array(['All EOG/EOC Subjects', 'All EOC Subjects', 'EOC Biology',
       'EOC English 2', 'EOC Math I', 'All EOG Subjects', 'EOG Grade 3',
       'EOG Grade 4', 'EOG Grade 5', 'EOG Grade 6', 'EOG Grade 7',
       'EOG Grade 8', 'EOG Reading Grades 3-8', 'EOG Reading Grade 3',
       'EOG Reading Grade 4', 'EOG Reading Grade 5',
       'EOG Reading Grade 6', 'EOG Reading Grade 7',
       'EOG Reading Grade 8', 'EOG Math Grades 3-8', 'EOG Math Grade 3',
       'EOG Math Grade 4', 'EOG Math Grade 5', 'EOG Math Grade 6',
       'EOG Math Grade 7', 'EOG Math Grade 8', 'EOG Science Grades 5&8',
       'EOG Science Grade 5', 'EOG Science Grade 8', 'Graduation Rate',
       'The ACT - Composite Score', 'The ACT - English',
       'The ACT - Reading', 'The ACT - Math', 'The ACT - Science',
       'The ACT - Writing', 'The ACT - All Subtests', 'Math Course Rigor',
       'ACT WorkKeys'], dtype=object)

In [22]:
char_meck_high = char_meck.loc[char_meck['Subject']== 'The ACT - Composite Score'][['School Name', 'School Code']].iloc[1:,]

In [31]:
char_meck_high.to_csv('char_meck_lea.csv')

In [39]:
charters = sixteen.loc[sixteen['District Name'] == 'Charter Schools']
charters = charters.loc[charters['Subject']== 'The ACT - Composite Score']
charters = charters.loc[charters['SBE District'] == 'Southwest']

In [40]:
charters

,District Name,School Code,School Name,SBE District,Subject,"Standard (CCR - Level 4 & 5, GLP - Level 3 & Above)",All Students,Female,Male,American Indian,...,American Indian.1,Asian.1,Black.1,Hispanic.1,Two or More Races.1,White.1,EDS.1,LEP.1,SWD.1,AIG.1
78907,Charter Schools,13A000,Carolina International School,Southwest,The ACT - Composite Score,Met UNC Minimum,47.7,59.3,29.4,NaN,...,10,10,11,10,10,23,10,10,10,10
80664,Charter Schools,36B000,Piedmont Community Charter School,Southwest,The ACT - Composite Score,Met UNC Minimum,61.4,61.7,61.1,NaN,...,10,10,10,10,10,63,10,10,10,10
80732,Charter Schools,36C000,Mountain Island Charter School,Southwest,The ACT - Composite Score,Met UNC Minimum,68.3,70.2,66.7,NaN,...,10,10,27,10,10,58,14,10,10,12
81588,Charter Schools,49E000,Pine Lake Preparatory,Southwest,The ACT - Composite Score,Met UNC Minimum,94.0,95.0,92.4,NaN,...,10,10,10,10,10,132,10,10,10,10
81922,Charter Schools,55A000,Lincoln Charter School,Southwest,The ACT - Composite Score,Met UNC Minimum,84.4,86.5,82.2,NaN,...,10,10,10,10,10,125,19,10,10,10
82054,Charter Schools,60B000,Sugar Creek Charter,Southwest,The ACT - Composite Score,Met UNC Minimum,38.2,47.1,29.4,NaN,...,10,10,32,10,10,10,33,10,10,10
82109,Charter Schools,60D000,Lake Norman Charter,Southwest,The ACT - Composite Score,Met UNC Minimum,94.8,95.0,93.2,NaN,...,10,10,19,11,10,151,10,10,10,10
82233,Charter Schools,60G000,Queen's Grant Community School,Southwest,The ACT - Composite Score,Met UNC Minimum,69.1,72.5,65.1,NaN,...,10,10,22,12,10,56,11,10,10,10
82301,Charter Schools,60I000,Community School of Davidson,Southwest,The ACT - Composite Score,Met UNC Minimum,94.0,92.9,95.0,NaN,...,10,10,10,10,10,101,10,10,15,10
82403,Charter Schools,60K000,Charlotte Secondary,Southwest,The ACT - Composite Score,Met UNC Minimum,49.0,47.4,50.0,NaN,...,10,10,25,10,10,13,10,10,10,10
82745,Charter Schools,60V000,Charlotte Learning Academy,Southwest,The ACT - Composite Score,Met UNC Minimum,7.1,5.0,13.3,NaN,...,10,10,25,10,10,10,17,10,10,10
84137,Charter Schools,84B000,Gray Stone Day,Southwest,The ACT - Composite Score,Met UNC Minimum,95.0,92.7,95.0,NaN,...,10,10,10,10,10,98,13,10,10,10
84374,Charter Schools,90A000,Union Academy,Southwest,The ACT - Composite Score,Met UNC Minimum,76.9,75.9,78.6,NaN,...,10,10,10,21,10,89,10,10,10,10